### ISSUE TITLE
update to new kemalyst-generator release once it's updated

### ISSUE THREAD

**Issue by andrewzah** [drujensen/homebrew-kgen#1]
There was a breaking change in Crystal's update which breaks `brew install kgen`.
https://github.com/crystal-lang/crystal/releases/tag/0.21.0

`Crypto::MD5` is now `Digest::MD5`

---

I submitted a pull-request in the repo, so now it's just time to wait for it to be updated.

**Comment by azah** [comment]
Made this issue in the wrong place.

**Comment by drujensen** [comment]
@azah should be fixed.  let me know if anything else is broken.

**Comment by andrewzah** [comment]
@drujensen `brew install kgen` works now, thanks.
